### ISSUE TITLE
How do I download this 

### ISSUE THREAD

**Issue by SaiasiZKS** [yanniknelson/Piet_Interpreter#1]
im new how do i use this?

**Comment by yanniknelson** [comment]
Hi apologies this is very much still in development. I don't have a lot of time to work on it right now.

**Comment by simortus** [comment]
you can download the git repo with the command line: 
git clone [this repo URL ]
Or simply download the zip file. 
I am happy to help. However, these questions are basic and can be googled.

**Comment by SaiasiZKS** [comment]
Oh okay! Sorry for the late response by the way.
